ADD_SCENE(hid_device, startscreen, Startscreen)
ADD_SCENE(hid_device, menu, Menu)
ADD_SCENE(hid_device, settings, Settings)
ADD_SCENE(hid_device, bt_pair, BtPair)
ADD_SCENE(hid_device, usb_debug_restart, UsbDebugRestart)
